name: MangaStats
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: favorite manga and currently watching
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.anilist.manga.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 5
          plugin_anilist_user: scumbagnyx
